name: restaurant_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  like_button: ^2.0.4
  http: ^0.13.4
  provider: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  flutter_native_splash: ^2.1.1

flutter_native_splash:
  color: "#795548"
  image: images/splash.png

flutter:

  uses-material-design: true

  assets:
    - assets/local_restaurant.json
    - images/

  fonts:
    - family: Staatliches
      fonts:
        - asset: fonts/Staatliches/Staatliches-Regular.ttf
    - family: Oxygen
      fonts:
        - asset: fonts/Oxygen/Oxygen-Regular.ttf